### ISSUE TITLE
Letter-spacing values don't match Inter's Dynamic Metrics

### ISSUE THREAD

**Issue by richardthombs** [semencov/tailwindcss-font-inter#8]
I don't think the calculated letter-spacing values are correct. Visually the spacing for all text other than font-base seems too wide:

![image](https://user-images.githubusercontent.com/1511599/109145215-1c455580-775a-11eb-980d-aa0c11d3b4c7.png)

The job title there is text-sm, which Chrome dev-tools shows to be `font-size: 14px`. The Dynamic Metrics page recommends a spacing of -0.006em for 14px text, but the spacing inserted by the plugin is `letter-spacing: 0.1627em` - much wider.

[Example on tailwindplay](https://play.tailwindcss.com/oUtxYHKN1l?layout=horizontal)

**Comment by semencov** [comment]
Thanks for the report, @richardthombs!

It looks like Tailwind 2 has a different default theme for the font sizes, so instead of a string, it brings an array with both font size and line height. I've added some type check so it should be fine now. Would you update the plugin to the v2.0.2 and test?

#9

**Comment by richardthombs** [comment]
Hi @semencov Yep that's fixed it. Thank you for such a fast turnaround! :smile:
